/// <reference path="../pb_data/types.d.ts" />
/**
 * Agency Meta integrations + generic social asset connections + metric snapshots.
 * Locked rules: server admin SDK only.
 * Also: node apps/web/scripts/add-social-meta-collections.mjs
 */
migrate((db) => {
  const dao = new Dao(db)

  let users
  try {
    users = dao.findCollectionByNameOrId('users')
  } catch (e) {
    users = dao.findCollectionByNameOrId('_pb_users_auth_')
  }

  const sites = dao.findCollectionByNameOrId('sites')

  try {
    dao.findCollectionByNameOrId('agency_integrations')
  } catch (e) {
    const integ = new Collection({
      id: 'aintmeta01wrr01',
      created: '2026-08-15 12:00:00.000Z',
      updated: '2026-08-15 12:00:00.000Z',
      name: 'agency_integrations',
      type: 'base',
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      schema: [
        {
          system: false,
          id: 'aintagency01',
          name: 'agency',
          type: 'relation',
          required: true,
          presentable: false,
          unique: false,
          options: {
            collectionId: users.id,
            cascadeDelete: true,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
        {
          system: false,
          id: 'aintprovid01',
          name: 'provider',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: { maxSelect: 1, values: ['meta'] },
        },
        {
          system: false,
          id: 'aintextuid01',
          name: 'external_user_id',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 128, pattern: '' },
        },
        {
          system: false,
          id: 'aintextbiz01',
          name: 'external_business_id',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 128, pattern: '' },
        },
        {
          system: false,
          id: 'aintdispnm01',
          name: 'display_name',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 200, pattern: '' },
        },
        {
          system: false,
          id: 'aintencacc01',
          name: 'encrypted_access_token',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 8000, pattern: '' },
        },
        {
          system: false,
          id: 'ainttokexp01',
          name: 'token_expires_at',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'aintscopes01',
          name: 'scopes',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 2000, pattern: '' },
        },
        {
          system: false,
          id: 'aintstatus01',
          name: 'status',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: {
            maxSelect: 1,
            values: ['connected', 'expired', 'reconnect_required', 'error', 'disconnected'],
          },
        },
        {
          system: false,
          id: 'aintlastvf01',
          name: 'last_verified_at',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'aintlaster01',
          name: 'last_error',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 500, pattern: '' },
        },
        {
          system: false,
          id: 'aintcreate01',
          name: 'created_by',
          type: 'relation',
          required: false,
          presentable: false,
          unique: false,
          options: {
            collectionId: users.id,
            cascadeDelete: false,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
        {
          system: false,
          id: 'aintupdate01',
          name: 'updated_by',
          type: 'relation',
          required: false,
          presentable: false,
          unique: false,
          options: {
            collectionId: users.id,
            cascadeDelete: false,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_agency_integrations_agency_provider ON agency_integrations (agency, provider)',
      ],
    })
    dao.saveCollection(integ)
  }

  const agencyIntegrations = dao.findCollectionByNameOrId('agency_integrations')

  try {
    dao.findCollectionByNameOrId('site_social_connections')
  } catch (e) {
    const conns = new Collection({
      id: 'ssoconn01wrr001',
      created: '2026-08-15 12:00:00.000Z',
      updated: '2026-08-15 12:00:00.000Z',
      name: 'site_social_connections',
      type: 'base',
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      schema: [
        {
          system: false,
          id: 'sscsite00001',
          name: 'site',
          type: 'relation',
          required: true,
          presentable: false,
          unique: false,
          options: {
            collectionId: sites.id,
            cascadeDelete: true,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
        {
          system: false,
          id: 'sscagint0001',
          name: 'agency_integration',
          type: 'relation',
          required: false,
          presentable: false,
          unique: false,
          options: {
            collectionId: agencyIntegrations.id,
            cascadeDelete: false,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
        {
          system: false,
          id: 'sscprovid001',
          name: 'provider',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: { maxSelect: 1, values: ['meta'] },
        },
        {
          system: false,
          id: 'sscplatfm001',
          name: 'platform',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: { maxSelect: 1, values: ['facebook', 'instagram'] },
        },
        {
          system: false,
          id: 'sscasset0001',
          name: 'asset_type',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: {
            maxSelect: 1,
            values: ['facebook_page', 'instagram_business_account', 'ad_account'],
          },
        },
        {
          system: false,
          id: 'sscacctype01',
          name: 'access_type',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: { maxSelect: 1, values: ['public', 'authenticated'] },
        },
        {
          system: false,
          id: 'sscextid0001',
          name: 'external_asset_id',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 200, pattern: '' },
        },
        {
          system: false,
          id: 'sscextpar001',
          name: 'external_parent_asset_id',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 200, pattern: '' },
        },
        {
          system: false,
          id: 'sscdispnm001',
          name: 'display_name',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 200, pattern: '' },
        },
        {
          system: false,
          id: 'sscusernm001',
          name: 'username',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 200, pattern: '' },
        },
        {
          system: false,
          id: 'ssccanonu001',
          name: 'canonical_url',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 500, pattern: '' },
        },
        {
          system: false,
          id: 'sscencpgk001',
          name: 'encrypted_page_token',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 8000, pattern: '' },
        },
        {
          system: false,
          id: 'sscstatus001',
          name: 'status',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: {
            maxSelect: 1,
            values: ['active', 'metrics_unavailable', 'reconnect_required', 'error', 'disconnected'],
          },
        },
        {
          system: false,
          id: 'ssclastsy001',
          name: 'last_synced_at',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'ssclaster001',
          name: 'last_error',
          type: 'text',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: 500, pattern: '' },
        },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_site_social_conn_site_asset ON site_social_connections (site, provider, platform, asset_type)',
        'CREATE INDEX idx_site_social_conn_ext_asset ON site_social_connections (external_asset_id)',
      ],
    })
    dao.saveCollection(conns)
  }

  const connections = dao.findCollectionByNameOrId('site_social_connections')

  try {
    dao.findCollectionByNameOrId('social_metric_snapshots')
  } catch (e) {
    const snaps = new Collection({
      id: 'smsnap01wrr0001',
      created: '2026-08-15 12:00:00.000Z',
      updated: '2026-08-15 12:00:00.000Z',
      name: 'social_metric_snapshots',
      type: 'base',
      system: false,
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      schema: [
        {
          system: false,
          id: 'smssite00001',
          name: 'site',
          type: 'relation',
          required: true,
          presentable: false,
          unique: false,
          options: {
            collectionId: sites.id,
            cascadeDelete: true,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
        {
          system: false,
          id: 'smsconn00001',
          name: 'social_connection',
          type: 'relation',
          required: true,
          presentable: false,
          unique: false,
          options: {
            collectionId: connections.id,
            cascadeDelete: false,
            minSelect: null,
            maxSelect: 1,
            displayFields: null,
          },
        },
        {
          system: false,
          id: 'smsprovid001',
          name: 'provider',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: { maxSelect: 1, values: ['meta'] },
        },
        {
          system: false,
          id: 'smsplatfm001',
          name: 'platform',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: { maxSelect: 1, values: ['facebook', 'instagram'] },
        },
        {
          system: false,
          id: 'smsasset0001',
          name: 'asset_type',
          type: 'select',
          required: true,
          presentable: false,
          unique: false,
          options: {
            maxSelect: 1,
            values: ['facebook_page', 'instagram_business_account', 'ad_account'],
          },
        },
        {
          system: false,
          id: 'smsmetkey001',
          name: 'metric_key',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 120, pattern: '' },
        },
        {
          system: false,
          id: 'smsvalue0001',
          name: 'value',
          type: 'number',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: null, noDecimal: false },
        },
        {
          system: false,
          id: 'smssource001',
          name: 'source',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 80, pattern: '' },
        },
        {
          system: false,
          id: 'smsisexact01',
          name: 'is_exact',
          type: 'bool',
          required: false,
          presentable: false,
          unique: false,
          options: {},
        },
        {
          system: false,
          id: 'smsconfid001',
          name: 'confidence',
          type: 'number',
          required: false,
          presentable: false,
          unique: false,
          options: { min: null, max: null, noDecimal: false },
        },
        {
          system: false,
          id: 'smspertyp001',
          name: 'period_type',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'smspersta001',
          name: 'period_start',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'smsperend001',
          name: 'period_end',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'smscollect01',
          name: 'collected_at',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'smssnapdt001',
          name: 'snapshot_date',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 40, pattern: '' },
        },
        {
          system: false,
          id: 'smsdedupe001',
          name: 'dedupe_key',
          type: 'text',
          required: true,
          presentable: false,
          unique: false,
          options: { min: null, max: 400, pattern: '' },
        },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_social_metric_snapshots_dedupe ON social_metric_snapshots (dedupe_key)',
        'CREATE INDEX idx_social_metric_snapshots_site_metric ON social_metric_snapshots (site, metric_key, snapshot_date)',
      ],
    })
    dao.saveCollection(snaps)
  }
}, (db) => {
  const dao = new Dao(db)
  try {
    dao.deleteCollection(dao.findCollectionByNameOrId('social_metric_snapshots'))
  } catch (e) {}
  try {
    dao.deleteCollection(dao.findCollectionByNameOrId('site_social_connections'))
  } catch (e) {}
  try {
    dao.deleteCollection(dao.findCollectionByNameOrId('agency_integrations'))
  } catch (e) {}
})
